# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywims_exos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo',
            name='layout',
            field=models.FileField(default='setting.MEDIA_ROOT/layouts/layout_standard.html', upload_to='layouts'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='apres',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='exo',
            name='avant',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='exo',
            name='enonce',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='exo',
            name='reponse',
            field=models.TextField(verbose_name=''),
        ),
    ]
