# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywims_exos', '0003_auto_20170606_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo',
            name='ggb',
            field=models.TextField(default='', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exo',
            name='layout',
            field=models.FilePathField(default='layout_standard.html', path='C:\\Etienne\\Python\\djangogirls\\pywims_exos/templates/pywims_exos/layouts'),
        ),
    ]
