# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywims_exos', '0004_auto_20170606_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exo',
            name='ggb',
        ),
        migrations.AddField(
            model_name='exo',
            name='ggb_commands',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exo',
            name='ggb_file',
            field=models.FileField(blank=True, default='', upload_to='ggb_files'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='apres',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exo',
            name='avant',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exo',
            name='enonce',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exo',
            name='layout',
            field=models.FilePathField(default='layout_standard.html', path='C:\\Etienne\\Python\\djangogirls\\pywims_exos\templates\\pywims_exos\\layouts'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='reponse',
            field=models.TextField(blank=True, default=''),
        ),
    ]
